### ISSUE TITLE
[bug] Freezing on bootup

### ISSUE THREAD

**Issue by YukihoAA** [misyaguziya/VRCT#22] opened 2024-09-05 06:56 UTC
![image](https://github.com/user-attachments/assets/929267e3-f4d5-457a-bf0f-d66d2169c439)

When I run VRCT, It freeze like image.

there is no log file in logs folder 

It happens both installer & archive version.

before window open, black-backgrounded-texts show up left top corner and some of them are my font's name.

Windows 11 Edu / 22631 Build.

AMD 5800X / 64GB / RTX 3080Ti

+ add

cannot run install.bat with error below
![image](https://github.com/user-attachments/assets/a626a28a-e9cd-499b-9d11-78d7c92803ac)

i installed python with installer but similler error occured
![image](https://github.com/user-attachments/assets/d8b94486-d61e-4514-ba74-ced5e7ccb60d)

**Comment by ShiinaSakamoto** [comment] 2024-09-06 05:10
Thank you for reporting. Okay, this happened again. I see...
We actually don't know why this happens yet.
I'll mark this issue as a duplicate and continue the conversation over there. Anyway, thanks.

Duplicate of #13

**Comment by ShiinaSakamoto** [comment] 2024-09-06 05:11
Duplicate of #13

**Comment by cheongpark** [comment] 2024-09-07 13:40
> ![image](https://private-user-images.githubusercontent.com/20253131/364658149-929267e3-f4d5-457a-bf0f-d66d2169c439.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MTY2MDUsIm5iZiI6MTcyNTcxNjMwNSwicGF0aCI6Ii8yMDI1MzEzMS8zNjQ2NTgxNDktOTI5MjY3ZTMtZjRkNS00NTdhLWJmMGYtZDY2ZDIxNjljNDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDEzMzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YjdmODg2NmIxZWQ4MTUwMmI2NmU4YmYzNTg1MTAzZmE4YmVjZDY4MmE2NmYzNWFhMjM1YTJkZWFhZDYxN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s_M6n65Oc5C7xrJnHc-yYn7a_waI1zBjnG2I1CrJcwE)
> 
> When I run VRCT, It freeze like image.
> 
> there is no log file in logs folder
> 
> It happens both installer & archive version.
> 
> before window open, black-backgrounded-texts show up left top corner and some of them are my font's name.
> 
> Windows 11 Edu / 22631 Build.
> 
> AMD 5800X / 64GB / RTX 3080Ti
> 
> * add
> 
> cannot run install.bat with error below ![image](https://private-user-images.githubusercontent.com/20253131/364662047-a626a28a-e9cd-499b-9d11-78d7c92803ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MTY2MDUsIm5iZiI6MTcyNTcxNjMwNSwicGF0aCI6Ii8yMDI1MzEzMS8zNjQ2NjIwNDctYTYyNmEyOGEtZTljZC00OTliLTlkMTEtNzhkN2M5MjgwM2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDEzMzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzM2IxODA2YjJmMThjNzkyZjdmOTc0NTkwYjZlYjVkMGMyNDYzOWNkM2ZjZTFlNTYxMGZlZjU3N2ZjZDU0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SS1IodZurJOS03ITrmrY34pBJk_flpIsSDgZWANq-c8)
> 
> i installed python with installer but similler error occured ![image](https://private-user-images.githubusercontent.com/20253131/364669041-d8b94486-d61e-4514-ba74-ced5e7ccb60d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MTY2MDUsIm5iZiI6MTcyNTcxNjMwNSwicGF0aCI6Ii8yMDI1MzEzMS8zNjQ2NjkwNDEtZDhiOTQ0ODYtZDYxZS00NTE0LWJhNzQtY2VkNWU3Y2NiNjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDEzMzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YmZhYzQ0NGQzMzNmZTVlNmM1YzA4M2I5MWIyNzEwZmI0ZjEyNDAxZWM4OTFkMzQ1MWZiYTgzNWJiMmViM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vTKjYbODowutB2qRKePjgd9oCqiZIez2Y1wpIQKu6lo)

Errors occurring during the installation of "sentencepiece==0.1.99" seem to be due to using Python version 3.12 instead of the recommended Python version 3.11.5 by the developer. It appears to be a different issue from the error where the GUI does not load, as shown in the first picture.

**Comment by YukihoAA** [comment] 2024-09-07 22:25
> > ![image](https://private-user-images.githubusercontent.com/20253131/364658149-929267e3-f4d5-457a-bf0f-d66d2169c439.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MTY2MDUsIm5iZiI6MTcyNTcxNjMwNSwicGF0aCI6Ii8yMDI1MzEzMS8zNjQ2NTgxNDktOTI5MjY3ZTMtZjRkNS00NTdhLWJmMGYtZDY2ZDIxNjljNDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDEzMzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YjdmODg2NmIxZWQ4MTUwMmI2NmU4YmYzNTg1MTAzZmE4YmVjZDY4MmE2NmYzNWFhMjM1YTJkZWFhZDYxN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s_M6n65Oc5C7xrJnHc-yYn7a_waI1zBjnG2I1CrJcwE)
> > When I run VRCT, It freeze like image.
> > there is no log file in logs folder
> > It happens both installer & archive version.
> > before window open, black-backgrounded-texts show up left top corner and some of them are my font's name.
> > Windows 11 Edu / 22631 Build.
> > AMD 5800X / 64GB / RTX 3080Ti
> > 
> > * add
> > 
> > cannot run install.bat with error below ![image](https://private-user-images.githubusercontent.com/20253131/364662047-a626a28a-e9cd-499b-9d11-78d7c92803ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MTY2MDUsIm5iZiI6MTcyNTcxNjMwNSwicGF0aCI6Ii8yMDI1MzEzMS8zNjQ2NjIwNDctYTYyNmEyOGEtZTljZC00OTliLTlkMTEtNzhkN2M5MjgwM2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDEzMzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzM2IxODA2YjJmMThjNzkyZjdmOTc0NTkwYjZlYjVkMGMyNDYzOWNkM2ZjZTFlNTYxMGZlZjU3N2ZjZDU0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SS1IodZurJOS03ITrmrY34pBJk_flpIsSDgZWANq-c8)
> > i installed python with installer but similler error occured ![image](https://private-user-images.githubusercontent.com/20253131/364669041-d8b94486-d61e-4514-ba74-ced5e7ccb60d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MTY2MDUsIm5iZiI6MTcyNTcxNjMwNSwicGF0aCI6Ii8yMDI1MzEzMS8zNjQ2NjkwNDEtZDhiOTQ0ODYtZDYxZS00NTE0LWJhNzQtY2VkNWU3Y2NiNjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDEzMzgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YmZhYzQ0NGQzMzNmZTVlNmM1YzA4M2I5MWIyNzEwZmI0ZjEyNDAxZWM4OTFkMzQ1MWZiYTgzNWJiMmViM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vTKjYbODowutB2qRKePjgd9oCqiZIez2Y1wpIQKu6lo)
> 
> Errors occurring during the installation of "sentencepiece==0.1.99" seem to be due to using Python version 3.12 instead of the recommended Python version 3.11.5 by the developer. It appears to be a different issue from the error where the GUI does not load, as shown in the first picture.

yes it is, so I tried 3.11.9 and worked fine excuting install.bat

**Closed** 2024-09-14 07:27 UTC
Labels: bug, duplicate
